INVALID_URL = ValueError("Invalid URL for bucket was provided")
